== PP-Module for Authentication Servers

[cols="1,1,1,1,1,1,1,1"]
|===
8+|authserver 
| https://github.com/commoncriteria/authserver/tree/master[master] 
a| https://commoncriteria.github.io/authserver/master/authserver-release.html[📄]
a|[link=https://github.com/commoncriteria/authserver/blob/gh-pages/master/ValidationReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/authserver/gh-pages/master/validation.svg[Validation]
a|[link=https://github.com/commoncriteria/authserver/blob/gh-pages/master/SanityChecksOutput.md]
image::https://raw.githubusercontent.com/commoncriteria/authserver/gh-pages/master/warnings.svg[SanityChecks]
a|[link=https://github.com/commoncriteria/authserver/blob/gh-pages/master/SpellCheckReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/authserver/gh-pages/master/spell-badge.svg[SpellCheck]
a|[link=https://github.com/commoncriteria/authserver/blob/gh-pages/master/TDValidationReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/authserver/gh-pages/master/tds.svg[TDs]
a|image::https://raw.githubusercontent.com/commoncriteria/authserver/gh-pages/master/transforms.svg[transforms,150]
a|
https://commoncriteria.github.io/authserver/master/authserver-esr.html[authserver-esr.html] +
https://commoncriteria.github.io/authserver/master/authserver-release-linkable.html[authserver-release-linkable.html] +
https://commoncriteria.github.io/authserver/master/authserver-release.html[authserver-release.html] +
https://commoncriteria.github.io/authserver/master/authserver.html[authserver.html] +
|===

https://github.com/commoncriteria/authserver/issues[image:https://img.shields.io/github/issues/commoncriteria/authserver.svg?maxAge=2592000[GitHub
issues Open]]
image:https://img.shields.io/badge/license-Unlicensed-blue.svg[license]

This repository hosts the draft version of the PP-Module for Authentication Servers based on the 
https://commoncriteria.github.io/authserver/master/authserver-esr.html[Essential Security Requirements (ESR)] for this technology class of 
products. This repository is used to facilitate collaboration and development on the draft document. 
See the link:#Release-Version[release] section if you are looking for the officially released version for evaluations. A list of products that have passed evaluation against this Protection Profile can be found https://www.niap-ccevs.org/Product/index.cfm[here].

=== Draft Version

* https://commoncriteria.github.io/authserver/master/authserver-release.html[PP-Module for Authentication Servers] (html)
* https://commoncriteria.github.io/authserver/master/authserver-sd.html[SD for Authentication Servers] (html)
* https://commoncriteria.github.io/authserver/master/authserver.html[Combined PP-Module and SD for Authentication Servers] (html)

=== Release Version

* https://www.niap-ccevs.org/protectionprofiles/470[PP-Module for Authentication Servers]

=== Contributing

If you are interested in contributing directly to future versions the this Protection Profile, please consider joining the NIAP technical community.
* https://www.niap-ccevs.org/NIAP_Evolution/tech_communities.cfm[How to
join the NIAP Technical Community (Mailing list and updates)]

=== Feedback

Questions, comments, and fixes can be submitted to the 
https://github.com/commoncriteria/authserver/issues[repository issue tracker]

=== Quickstart

To clone this project along with its _transforms_ submodule run:

....
  git clone --recursive git@github.com:commoncriteria/authserver.git
....

To pull updates from the upstream _transforms_ submodule and commit them run:

....
 git submodule update --remote transforms
 git add transforms
 git commit
....

==== Development Info

https://github.com/commoncriteria/transforms/wiki/Working-with-Transforms-as-a-Submodule[Help
working with Transforms Submodule]

=== Repository Content

* input - Contains the 'meat' of the project. It's the input content (in XML form) that gets transformed to readable html.
* output - The output directory where the html is placed after transformation.
* output/images - The directory where images are stored
* transforms - Points to the transform subproject which is really a repository for resources shared amongst many Common Criteria projects.

=== Links 
* https://www.niap-ccevs.org/[National Information Assurance Partnership
(NIAP)]
* https://www.commoncriteriaportal.org/[Common Criteria Portal]

=== License

See link:./LICENSE[License]
